Project_SUNDARBANS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('sundarbans.urls')),
    path('accounts/', include('accounts.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(),name='signup_'),
]

sundarbans/urls.py
from django.urls import path
from .views import HomePageView, WildLifeView, GuideView, SpotView ,BookingFormView

urlpatterns = [
    path('', HomePageView.as_view(), name='home_'),
    path('wildlife/', WildLifeView.as_view(), name='wildlife_'),
    path('guide/', GuideView.as_view(), name='guide_'),
    path('spot/', SpotView.as_view(), name='spot_'),
    path('form/',BookingFormView, name = 'form_')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class CustomUser(AbstractUser):
    email = models.EmailField(max_length=254)
    phone_no = models.CharField(max_length=254)
    country = models.CharField(max_length=254)

sundarbans/models.py
from django.db import models
from django_countries.fields import CountryField


# Create your models here.
class WildLife(models.Model):
    w_id = models.CharField(primary_key=True, max_length=254)
    w_name = models.CharField(max_length=254)
    w_type = models.CharField(blank=True, null=True, max_length=254)
    w_pic = models.ImageField(blank=True, null=True)


class Guide(models.Model):
    g_id = models.CharField(primary_key=True, max_length=254)
    g_name = models.CharField(max_length=254)
    g_contact = models.CharField(max_length=254)
    g_email = models.EmailField()
    g_rating = models.IntegerField(null=True, blank=True)


class Spot(models.Model):
    s_id = models.CharField(primary_key=True, max_length=254)
    s_name = models.CharField(max_length=254)
    s_description = models.TextField(null=True, blank=True)
    s_pic = models.ImageField(blank=True, null=True)


class Booking(models.Model):
    choice = (('Primary', 'Primary'), ('Standard', 'Standard'), ('Combo', 'Combo'))
    package = models.CharField(max_length=254, choices=choice)
    name = models.CharField(max_length=254)
    country = CountryField()
    email = models.EmailField()
    phone = models.CharField(max_length=254)
    start_date = models.DateField()
    end_date = models.DateField()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'phone_no', 'country')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'phone_no', 'country')

sundarbans/forms.py
from django import forms
from django.forms import ModelForm
from .models import Booking


class DateInput(forms.DateInput):
    input_type = 'date'


class BookingForm(ModelForm):
    class Meta:
        model = Booking
        fields = ['package',
                  'name',
                  'country',
                  'email',
                  'phone',
                  'start_date',
                  'end_date'
        ]
        widgets = {
            'start_date': DateInput(),
            'end_date': DateInput(),
        }

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


# Create your views here.
class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

sundarbans/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, FormView
from .models import WildLife, Guide, Spot
from .forms import BookingForm


# Create your views here.
class HomePageView(TemplateView):
    template_name = 'home.html'


class WildLifeView(ListView):
    model = WildLife
    template_name = 'sundarbans/wildlife.html'


class GuideView(ListView):
    model = Guide
    template_name = 'sundarbans/guide.html'


class SpotView(ListView):
    model = Spot
    template_name = 'sundarbans/spot.html'


# @login_required
@permission_required(perm='',login_url='login')
def BookingFormView(request):
    form = BookingForm()
    login_url = 'login'
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('home_')
    return render(request, 'booking form.html', {'form': form})

templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="container">
        <div class="jumbotron">
            <h2 style="text-align: center">Create Account!</h2>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-outline-info" type="submit" >Sign Up</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- <link rel="stylesheet"  href="{% static 'css/base.css' %}"> -->

</head>
<body>
<!-- navbar-->
<nav class="navbar navbar-expand-lg " style="background: cornflowerblue ">
    <ul class="navbar-nav ">
        <li class="nav-item active pr-2"><a href="{% url 'home_' %}" style="color: black; "><h6>Home |</h6></a></li>
        <li class="nav-item pr-2 "><a href="{% url 'wildlife_' %}" style="color: black;"><h6>Wildlife |</h6></a></li>
        <li class="nav-item pr-2"><a href="{% url 'spot_' %}" style="color: black;"><h6> Spots |</h6></a></li>
        <li class="nav-item pr-2"><a href="{% url 'guide_' %}" style="color: black;"><h6> Guides </h6></a></li>
    </ul>
    <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
            <div class=" dropdown">
                <button type="button" class="btn btn-outline-secondary dropdown-toggle " data-toggle="dropdown">
                    {{ user.username }}
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                </div>
            </div>

        {% else %}
            <ul class="navbar-nav">
                <li class="nav-item pr-1">
                    <a class="nav-link btn btn-outline-success" style="color: black" href="{% url 'signup_' %}">Sign
                        Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-outline-primary" style="color: black" href="{% url 'login' %}">Login</a>
                </li>
            </ul>

        {% endif %}
    </ul>

</nav>

{% block content %}
{% endblock content %}
</body>
</html>

templates/booking form.html
{% extends 'base.html' %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="container">
        <div class="jumbotron" style="background: lightpink">
            <h1 style="text-align: center;font-family: Candara ">Book a package tour!!</h1>

            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit">
            </form>

        </div>
    </div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <body style="background: lightgreen ">
    <div class="container mt-lg-auto">
        <div class="jumbotron" style="background: lightgreen ; padding-top: 1rem">
            <h1 style="color: red; font-size: 3rem">Sundarbans</h1>
            <h5>The biggest mangrove forest in the world!</h5>
            <br>

            <!--carousel-->
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <!-- pics -->
                <div class="carousel-inner" style="width: auto;height: 25rem">
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="/media/carosol_pics/tiger-01.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="/media/carosol_pics/deer-05.jpg" alt="Third slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="/media/carosol_pics/crocodile-02.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>

    <!------------------------------------------------ second section ---------------------------------------------------->
    <div class="container">
        <div class="jumbotron">
            <h2 style="text-align: center;margin-bottom: inherit; color: darkviolet ">Tour Packages </h2>
            <!--Carousel Wrapper-->
            <div id="multi-item-example" class="carousel slide carousel-multi-item" data-ride="carousel">

                <!--Controls-->
                <div class="controls-top">
                    <a class="btn-floating" href="#multi-item-example" data-slide="prev"><i
                            class="fas fa-chevron-left"></i></a>
                    <a class="btn-floating" href="#multi-item-example" data-slide="next"><i
                            class="fas fa-chevron-right"></i></a>
                </div>
                <!--/.Controls-->

                <!--Slides-->
                <div class="carousel-inner" role="listbox">

                    <!--First slide-->
                    <div class="col-md-4" style="float:left">
                        <div class="card mb-2">
                            <img class="card-img-top"
                                 src="/media/karam_jol.jpg"
                                 alt="Card image cap">
                            <div class="card-body">
                                <h4 class="card-title">Combo Package</h4>
                                <p class="card-text">Hiron Point, Karamjal <br> Dublar Char, Katka</p>

                            </div>
                        </div>
                    </div>

                    <div class="col-md-4" style="float:left">
                        <div class="card mb-2">
                            <img class="card-img-top"
                                 src="/media/Dublar_Char.jpg"
                                 alt="Card image cap">
                            <div class="card-body">
                                <h4 class="card-title">Standard Package</h4>
                                <p class="card-text">Hiron Point, Karamjal <br> Dublar Char</p>

                            </div>
                        </div>
                    </div>

                    <div class="col-md-4" style="float:left">
                        <div class="card mb-2">
                            <img class="card-img-top"
                                 src="/media/hiran_point.jpg"
                                 alt="Card image cap">
                            <div class="card-body">
                                <h4 class="card-title">Primary Package</h4>
                                <p class="card-text">Hiron Point <br> Karamjal</p>

                            </div>
                        </div>
                    </div>
                    <!--/.First slide-->
                </div>
                <!--/.Slides-->
            </div>
            <!--/.Carousel Wrapper-->
            <div style="text-align: center; padding-top: 1rem">
                <a href="{% url 'form_' %}">
                    <button class="btn btn-outline-primary" style=" border-radius: 10%; font-size: 1.2rem ">Book a Package</button>
                </a>
            </div>
        </div>
    </div>


    <footer class="navbar navbar-nav navbar-light">
        <p>Developer Contact: Suprove Chandra Sarkar | Email: u1704099@student.cuet.ac.bd
    </footer>

    </body>
{% endblock content %}

templates/sundarbans/guide.html
{% extends 'base.html' %}
{% block content %}
<div class="container pb-lg-5">
    <table border="2" cellpadding="10rem" width="100%">
        <tr style="background: lightsalmon"><td colspan="5"><h2>Guide Details</h2></td></tr>
        <tr style="background: lightyellow">
            <td>Guide_ID</td>
            <td>Name</td>
            <td>Contact no</td>
            <td>Email</td>
            <td>Rating</td>
        </tr>
        {% for x in guide_list %}
            <tr>
                <td>{{ x.g_id }}</td>
                <td>{{ x.g_name }}</td>
                <td>{{ x.g_contact }}</td>
                <td>{{ x.g_email }}</td>
                <td>{{ x.g_rating }}</td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

templates/sundarbans/spot.html
{% extends 'base.html' %}
{% block content %}
    <div class="container pb-lg-5">
        <table border="2" cellpadding="10rem" width="100%">
            <tr style="background: lightpink">
                <td colspan="5"><h2 style="color: black">Tourist Spots in Sundarbans</h2></td>
            </tr>
            <tr style="background: lightyellow; padding-left: initial">
                <td style="text-align: center">Spot_ID</td>
                <td style="text-align: center">Spot Name</td>
                <td style="text-align: center">Spot Description</td>
                <td style="text-align: center">Picture</td>
            </tr>
            {% for x in spot_list %}
                <tr>
                    <td style="text-align: center">{{ x.s_id }}</td>
                    <td style="text-align: center; width: 10rem; "><b>{{ x.s_name }}</b></td>
                    <td style="text-align: center">{{ x.s_description }}</td>
                    {% if x.s_pic %}
                        <td style="text-align: center"><img width="250rem" src="{{ x.s_pic.url }}"></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/sundarbans/wildlife.html
{% extends 'base.html' %}
{% block content %}
    <div class="container pb-lg-5">
        <div>
            <table border="2" cellpadding="8rem" width="100%">

                <tr style="background: lightgreen">
                    <td colspan="5"><h2 style="color: black">Wildlife of Sundarbans</h2></td>
                </tr>
                <tr style="background: lightgoldenrodyellow;">
                    <td>Wildlife_Id</td>
                    <td>Name</td>
                    <td>Type</td>
                    <td>Picture</td>
                </tr>
                {% for x in wildlife_list %}
                    <tr>
                        <td>{{ x.w_id }}</td>
                        <td>{{ x.w_name }}</td>
                        <td>{{ x.w_type }}</td>
                        {% if x.w_pic %}
                            <td align="center"><img width="150rem" src="{{ x.w_pic.url }}"></td>
                        {% endif %}

                    </tr>

                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}